# Generated by Django 4.2.18 on 2025-01-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_reference', models.CharField(max_length=50, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('product_type', models.CharField(choices=[('HOME', 'HOME'), ('BEAUTY', 'BEAUTY'), ('COMMERCIAL', 'COMMERCIAL')], max_length=50)),
                ('customer_age', models.IntegerField()),
                ('risk_postcode', models.CharField(max_length=20)),
                ('building_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contents_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quote_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conversion_status', models.CharField(choices=[('QUOTED', 'QUOTED'), ('ACCEPTED', 'ACCEPTED'), ('LAPSED', 'LAPSED')], max_length=20)),
                ('payment_type', models.CharField(choices=[('ANNUAL', 'ANNUAL'), ('MONTHLY', 'MONTHLY')], max_length=20)),
                ('broker_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('suspicious', models.BooleanField(default=False)),
            ],
        ),
    ]
