# Generated by Django 4.2.18 on 2025-01-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_method', models.CharField(max_length=10)),
                ('request_url', models.CharField(max_length=600)),
                ('request_headers', models.TextField()),
                ('request_body', models.TextField()),
                ('response_status', models.IntegerField()),
                ('response_body', models.TextField()),
            ],
        ),
    ]
